<html>
<head>
<title>_ufunc_config.py</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
.s0 { color: #629755; font-style: italic;}
.s1 { color: #a9b7c6;}
.s2 { color: #cc7832;}
.s3 { color: #6a8759;}
.s4 { color: #6897bb;}
.s5 { color: #808080;}
</style>
</head>
<body bgcolor="#2b2b2b">
<table CELLSPACING=0 CELLPADDING=5 COLS=1 WIDTH="100%" BGCOLOR="#606060" >
<tr><td><center>
<font face="Arial, Helvetica" color="#000000">
_ufunc_config.py</font>
</center></td></tr></table>
<pre><span class="s0">&quot;&quot;&quot; 
Functions for changing global ufunc configuration 
 
This provides helpers which wrap `umath.geterrobj` and `umath.seterrobj` 
&quot;&quot;&quot;</span>
<span class="s2">import </span><span class="s1">collections.abc</span>
<span class="s2">import </span><span class="s1">contextlib</span>

<span class="s2">from </span><span class="s1">.overrides </span><span class="s2">import </span><span class="s1">set_module</span>
<span class="s2">from </span><span class="s1">.umath </span><span class="s2">import </span><span class="s1">(</span>
    <span class="s1">UFUNC_BUFSIZE_DEFAULT</span><span class="s2">,</span>
    <span class="s1">ERR_IGNORE</span><span class="s2">, </span><span class="s1">ERR_WARN</span><span class="s2">, </span><span class="s1">ERR_RAISE</span><span class="s2">, </span><span class="s1">ERR_CALL</span><span class="s2">, </span><span class="s1">ERR_PRINT</span><span class="s2">, </span><span class="s1">ERR_LOG</span><span class="s2">, </span><span class="s1">ERR_DEFAULT</span><span class="s2">,</span>
    <span class="s1">SHIFT_DIVIDEBYZERO</span><span class="s2">, </span><span class="s1">SHIFT_OVERFLOW</span><span class="s2">, </span><span class="s1">SHIFT_UNDERFLOW</span><span class="s2">, </span><span class="s1">SHIFT_INVALID</span><span class="s2">,</span>
<span class="s1">)</span>
<span class="s2">from </span><span class="s1">. </span><span class="s2">import </span><span class="s1">umath</span>

<span class="s1">__all__ = [</span>
    <span class="s3">&quot;seterr&quot;</span><span class="s2">, </span><span class="s3">&quot;geterr&quot;</span><span class="s2">, </span><span class="s3">&quot;setbufsize&quot;</span><span class="s2">, </span><span class="s3">&quot;getbufsize&quot;</span><span class="s2">, </span><span class="s3">&quot;seterrcall&quot;</span><span class="s2">, </span><span class="s3">&quot;geterrcall&quot;</span><span class="s2">,</span>
    <span class="s3">&quot;errstate&quot;</span><span class="s2">,</span>
<span class="s1">]</span>

<span class="s1">_errdict = {</span><span class="s3">&quot;ignore&quot;</span><span class="s1">: ERR_IGNORE</span><span class="s2">,</span>
            <span class="s3">&quot;warn&quot;</span><span class="s1">: ERR_WARN</span><span class="s2">,</span>
            <span class="s3">&quot;raise&quot;</span><span class="s1">: ERR_RAISE</span><span class="s2">,</span>
            <span class="s3">&quot;call&quot;</span><span class="s1">: ERR_CALL</span><span class="s2">,</span>
            <span class="s3">&quot;print&quot;</span><span class="s1">: ERR_PRINT</span><span class="s2">,</span>
            <span class="s3">&quot;log&quot;</span><span class="s1">: ERR_LOG}</span>

<span class="s1">_errdict_rev = {value: key </span><span class="s2">for </span><span class="s1">key</span><span class="s2">, </span><span class="s1">value </span><span class="s2">in </span><span class="s1">_errdict.items()}</span>


<span class="s1">@set_module(</span><span class="s3">'numpy'</span><span class="s1">)</span>
<span class="s2">def </span><span class="s1">seterr(all=</span><span class="s2">None, </span><span class="s1">divide=</span><span class="s2">None, </span><span class="s1">over=</span><span class="s2">None, </span><span class="s1">under=</span><span class="s2">None, </span><span class="s1">invalid=</span><span class="s2">None</span><span class="s1">):</span>
    <span class="s0">&quot;&quot;&quot; 
    Set how floating-point errors are handled. 
 
    Note that operations on integer scalar types (such as `int16`) are 
    handled like floating point, and are affected by these settings. 
 
    Parameters 
    ---------- 
    all : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional 
        Set treatment for all types of floating-point errors at once: 
 
        - ignore: Take no action when the exception occurs. 
        - warn: Print a `RuntimeWarning` (via the Python `warnings` module). 
        - raise: Raise a `FloatingPointError`. 
        - call: Call a function specified using the `seterrcall` function. 
        - print: Print a warning directly to ``stdout``. 
        - log: Record error in a Log object specified by `seterrcall`. 
 
        The default is not to change the current behavior. 
    divide : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional 
        Treatment for division by zero. 
    over : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional 
        Treatment for floating-point overflow. 
    under : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional 
        Treatment for floating-point underflow. 
    invalid : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional 
        Treatment for invalid floating-point operation. 
 
    Returns 
    ------- 
    old_settings : dict 
        Dictionary containing the old settings. 
 
    See also 
    -------- 
    seterrcall : Set a callback function for the 'call' mode. 
    geterr, geterrcall, errstate 
 
    Notes 
    ----- 
    The floating-point exceptions are defined in the IEEE 754 standard [1]_: 
 
    - Division by zero: infinite result obtained from finite numbers. 
    - Overflow: result too large to be expressed. 
    - Underflow: result so close to zero that some precision 
      was lost. 
    - Invalid operation: result is not an expressible number, typically 
      indicates that a NaN was produced. 
 
    .. [1] https://en.wikipedia.org/wiki/IEEE_754 
 
    Examples 
    -------- 
    &gt;&gt;&gt; old_settings = np.seterr(all='ignore')  #seterr to known value 
    &gt;&gt;&gt; np.seterr(over='raise') 
    {'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'} 
    &gt;&gt;&gt; np.seterr(**old_settings)  # reset to default 
    {'divide': 'ignore', 'over': 'raise', 'under': 'ignore', 'invalid': 'ignore'} 
 
    &gt;&gt;&gt; np.int16(32000) * np.int16(3) 
    30464 
    &gt;&gt;&gt; old_settings = np.seterr(all='warn', over='raise') 
    &gt;&gt;&gt; np.int16(32000) * np.int16(3) 
    Traceback (most recent call last): 
      File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt; 
    FloatingPointError: overflow encountered in short_scalars 
 
    &gt;&gt;&gt; old_settings = np.seterr(all='print') 
    &gt;&gt;&gt; np.geterr() 
    {'divide': 'print', 'over': 'print', 'under': 'print', 'invalid': 'print'} 
    &gt;&gt;&gt; np.int16(32000) * np.int16(3) 
    30464 
 
    &quot;&quot;&quot;</span>

    <span class="s1">pyvals = umath.geterrobj()</span>
    <span class="s1">old = geterr()</span>

    <span class="s2">if </span><span class="s1">divide </span><span class="s2">is None</span><span class="s1">:</span>
        <span class="s1">divide = all </span><span class="s2">or </span><span class="s1">old[</span><span class="s3">'divide'</span><span class="s1">]</span>
    <span class="s2">if </span><span class="s1">over </span><span class="s2">is None</span><span class="s1">:</span>
        <span class="s1">over = all </span><span class="s2">or </span><span class="s1">old[</span><span class="s3">'over'</span><span class="s1">]</span>
    <span class="s2">if </span><span class="s1">under </span><span class="s2">is None</span><span class="s1">:</span>
        <span class="s1">under = all </span><span class="s2">or </span><span class="s1">old[</span><span class="s3">'under'</span><span class="s1">]</span>
    <span class="s2">if </span><span class="s1">invalid </span><span class="s2">is None</span><span class="s1">:</span>
        <span class="s1">invalid = all </span><span class="s2">or </span><span class="s1">old[</span><span class="s3">'invalid'</span><span class="s1">]</span>

    <span class="s1">maskvalue = ((_errdict[divide] &lt;&lt; SHIFT_DIVIDEBYZERO) +</span>
                 <span class="s1">(_errdict[over] &lt;&lt; SHIFT_OVERFLOW) +</span>
                 <span class="s1">(_errdict[under] &lt;&lt; SHIFT_UNDERFLOW) +</span>
                 <span class="s1">(_errdict[invalid] &lt;&lt; SHIFT_INVALID))</span>

    <span class="s1">pyvals[</span><span class="s4">1</span><span class="s1">] = maskvalue</span>
    <span class="s1">umath.seterrobj(pyvals)</span>
    <span class="s2">return </span><span class="s1">old</span>


<span class="s1">@set_module(</span><span class="s3">'numpy'</span><span class="s1">)</span>
<span class="s2">def </span><span class="s1">geterr():</span>
    <span class="s0">&quot;&quot;&quot; 
    Get the current way of handling floating-point errors. 
 
    Returns 
    ------- 
    res : dict 
        A dictionary with keys &quot;divide&quot;, &quot;over&quot;, &quot;under&quot;, and &quot;invalid&quot;, 
        whose values are from the strings &quot;ignore&quot;, &quot;print&quot;, &quot;log&quot;, &quot;warn&quot;, 
        &quot;raise&quot;, and &quot;call&quot;. The keys represent possible floating-point 
        exceptions, and the values define how these exceptions are handled. 
 
    See Also 
    -------- 
    geterrcall, seterr, seterrcall 
 
    Notes 
    ----- 
    For complete documentation of the types of floating-point exceptions and 
    treatment options, see `seterr`. 
 
    Examples 
    -------- 
    &gt;&gt;&gt; np.geterr() 
    {'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'} 
    &gt;&gt;&gt; np.arange(3.) / np.arange(3.) 
    array([nan,  1.,  1.]) 
 
    &gt;&gt;&gt; oldsettings = np.seterr(all='warn', over='raise') 
    &gt;&gt;&gt; np.geterr() 
    {'divide': 'warn', 'over': 'raise', 'under': 'warn', 'invalid': 'warn'} 
    &gt;&gt;&gt; np.arange(3.) / np.arange(3.) 
    array([nan,  1.,  1.]) 
 
    &quot;&quot;&quot;</span>
    <span class="s1">maskvalue = umath.geterrobj()[</span><span class="s4">1</span><span class="s1">]</span>
    <span class="s1">mask = </span><span class="s4">7</span>
    <span class="s1">res = {}</span>
    <span class="s1">val = (maskvalue &gt;&gt; SHIFT_DIVIDEBYZERO) &amp; mask</span>
    <span class="s1">res[</span><span class="s3">'divide'</span><span class="s1">] = _errdict_rev[val]</span>
    <span class="s1">val = (maskvalue &gt;&gt; SHIFT_OVERFLOW) &amp; mask</span>
    <span class="s1">res[</span><span class="s3">'over'</span><span class="s1">] = _errdict_rev[val]</span>
    <span class="s1">val = (maskvalue &gt;&gt; SHIFT_UNDERFLOW) &amp; mask</span>
    <span class="s1">res[</span><span class="s3">'under'</span><span class="s1">] = _errdict_rev[val]</span>
    <span class="s1">val = (maskvalue &gt;&gt; SHIFT_INVALID) &amp; mask</span>
    <span class="s1">res[</span><span class="s3">'invalid'</span><span class="s1">] = _errdict_rev[val]</span>
    <span class="s2">return </span><span class="s1">res</span>


<span class="s1">@set_module(</span><span class="s3">'numpy'</span><span class="s1">)</span>
<span class="s2">def </span><span class="s1">setbufsize(size):</span>
    <span class="s0">&quot;&quot;&quot; 
    Set the size of the buffer used in ufuncs. 
 
    Parameters 
    ---------- 
    size : int 
        Size of buffer. 
 
    &quot;&quot;&quot;</span>
    <span class="s2">if </span><span class="s1">size &gt; </span><span class="s4">10e6</span><span class="s1">:</span>
        <span class="s2">raise </span><span class="s1">ValueError(</span><span class="s3">&quot;Buffer size, %s, is too big.&quot; </span><span class="s1">% size)</span>
    <span class="s2">if </span><span class="s1">size &lt; </span><span class="s4">5</span><span class="s1">:</span>
        <span class="s2">raise </span><span class="s1">ValueError(</span><span class="s3">&quot;Buffer size, %s, is too small.&quot; </span><span class="s1">% size)</span>
    <span class="s2">if </span><span class="s1">size % </span><span class="s4">16 </span><span class="s1">!= </span><span class="s4">0</span><span class="s1">:</span>
        <span class="s2">raise </span><span class="s1">ValueError(</span><span class="s3">&quot;Buffer size, %s, is not a multiple of 16.&quot; </span><span class="s1">% size)</span>

    <span class="s1">pyvals = umath.geterrobj()</span>
    <span class="s1">old = getbufsize()</span>
    <span class="s1">pyvals[</span><span class="s4">0</span><span class="s1">] = size</span>
    <span class="s1">umath.seterrobj(pyvals)</span>
    <span class="s2">return </span><span class="s1">old</span>


<span class="s1">@set_module(</span><span class="s3">'numpy'</span><span class="s1">)</span>
<span class="s2">def </span><span class="s1">getbufsize():</span>
    <span class="s0">&quot;&quot;&quot; 
    Return the size of the buffer used in ufuncs. 
 
    Returns 
    ------- 
    getbufsize : int 
        Size of ufunc buffer in bytes. 
 
    &quot;&quot;&quot;</span>
    <span class="s2">return </span><span class="s1">umath.geterrobj()[</span><span class="s4">0</span><span class="s1">]</span>


<span class="s1">@set_module(</span><span class="s3">'numpy'</span><span class="s1">)</span>
<span class="s2">def </span><span class="s1">seterrcall(func):</span>
    <span class="s0">&quot;&quot;&quot; 
    Set the floating-point error callback function or log object. 
 
    There are two ways to capture floating-point error messages.  The first 
    is to set the error-handler to 'call', using `seterr`.  Then, set 
    the function to call using this function. 
 
    The second is to set the error-handler to 'log', using `seterr`. 
    Floating-point errors then trigger a call to the 'write' method of 
    the provided object. 
 
    Parameters 
    ---------- 
    func : callable f(err, flag) or object with write method 
        Function to call upon floating-point errors ('call'-mode) or 
        object whose 'write' method is used to log such message ('log'-mode). 
 
        The call function takes two arguments. The first is a string describing 
        the type of error (such as &quot;divide by zero&quot;, &quot;overflow&quot;, &quot;underflow&quot;, 
        or &quot;invalid value&quot;), and the second is the status flag.  The flag is a 
        byte, whose four least-significant bits indicate the type of error, one 
        of &quot;divide&quot;, &quot;over&quot;, &quot;under&quot;, &quot;invalid&quot;:: 
 
          [0 0 0 0 divide over under invalid] 
 
        In other words, ``flags = divide + 2*over + 4*under + 8*invalid``. 
 
        If an object is provided, its write method should take one argument, 
        a string. 
 
    Returns 
    ------- 
    h : callable, log instance or None 
        The old error handler. 
 
    See Also 
    -------- 
    seterr, geterr, geterrcall 
 
    Examples 
    -------- 
    Callback upon error: 
 
    &gt;&gt;&gt; def err_handler(type, flag): 
    ...     print(&quot;Floating point error (%s), with flag %s&quot; % (type, flag)) 
    ... 
 
    &gt;&gt;&gt; saved_handler = np.seterrcall(err_handler) 
    &gt;&gt;&gt; save_err = np.seterr(all='call') 
 
    &gt;&gt;&gt; np.array([1, 2, 3]) / 0.0 
    Floating point error (divide by zero), with flag 1 
    array([inf, inf, inf]) 
 
    &gt;&gt;&gt; np.seterrcall(saved_handler) 
    &lt;function err_handler at 0x...&gt; 
    &gt;&gt;&gt; np.seterr(**save_err) 
    {'divide': 'call', 'over': 'call', 'under': 'call', 'invalid': 'call'} 
 
    Log error message: 
 
    &gt;&gt;&gt; class Log: 
    ...     def write(self, msg): 
    ...         print(&quot;LOG: %s&quot; % msg) 
    ... 
 
    &gt;&gt;&gt; log = Log() 
    &gt;&gt;&gt; saved_handler = np.seterrcall(log) 
    &gt;&gt;&gt; save_err = np.seterr(all='log') 
 
    &gt;&gt;&gt; np.array([1, 2, 3]) / 0.0 
    LOG: Warning: divide by zero encountered in true_divide 
    array([inf, inf, inf]) 
 
    &gt;&gt;&gt; np.seterrcall(saved_handler) 
    &lt;numpy.core.numeric.Log object at 0x...&gt; 
    &gt;&gt;&gt; np.seterr(**save_err) 
    {'divide': 'log', 'over': 'log', 'under': 'log', 'invalid': 'log'} 
 
    &quot;&quot;&quot;</span>
    <span class="s2">if </span><span class="s1">func </span><span class="s2">is not None and not </span><span class="s1">isinstance(func</span><span class="s2">, </span><span class="s1">collections.abc.Callable):</span>
        <span class="s2">if </span><span class="s1">(</span><span class="s2">not </span><span class="s1">hasattr(func</span><span class="s2">, </span><span class="s3">'write'</span><span class="s1">) </span><span class="s2">or</span>
                <span class="s2">not </span><span class="s1">isinstance(func.write</span><span class="s2">, </span><span class="s1">collections.abc.Callable)):</span>
            <span class="s2">raise </span><span class="s1">ValueError(</span><span class="s3">&quot;Only callable can be used as callback&quot;</span><span class="s1">)</span>
    <span class="s1">pyvals = umath.geterrobj()</span>
    <span class="s1">old = geterrcall()</span>
    <span class="s1">pyvals[</span><span class="s4">2</span><span class="s1">] = func</span>
    <span class="s1">umath.seterrobj(pyvals)</span>
    <span class="s2">return </span><span class="s1">old</span>


<span class="s1">@set_module(</span><span class="s3">'numpy'</span><span class="s1">)</span>
<span class="s2">def </span><span class="s1">geterrcall():</span>
    <span class="s0">&quot;&quot;&quot; 
    Return the current callback function used on floating-point errors. 
 
    When the error handling for a floating-point error (one of &quot;divide&quot;, 
    &quot;over&quot;, &quot;under&quot;, or &quot;invalid&quot;) is set to 'call' or 'log', the function 
    that is called or the log instance that is written to is returned by 
    `geterrcall`. This function or log instance has been set with 
    `seterrcall`. 
 
    Returns 
    ------- 
    errobj : callable, log instance or None 
        The current error handler. If no handler was set through `seterrcall`, 
        ``None`` is returned. 
 
    See Also 
    -------- 
    seterrcall, seterr, geterr 
 
    Notes 
    ----- 
    For complete documentation of the types of floating-point exceptions and 
    treatment options, see `seterr`. 
 
    Examples 
    -------- 
    &gt;&gt;&gt; np.geterrcall()  # we did not yet set a handler, returns None 
 
    &gt;&gt;&gt; oldsettings = np.seterr(all='call') 
    &gt;&gt;&gt; def err_handler(type, flag): 
    ...     print(&quot;Floating point error (%s), with flag %s&quot; % (type, flag)) 
    &gt;&gt;&gt; oldhandler = np.seterrcall(err_handler) 
    &gt;&gt;&gt; np.array([1, 2, 3]) / 0.0 
    Floating point error (divide by zero), with flag 1 
    array([inf, inf, inf]) 
 
    &gt;&gt;&gt; cur_handler = np.geterrcall() 
    &gt;&gt;&gt; cur_handler is err_handler 
    True 
 
    &quot;&quot;&quot;</span>
    <span class="s2">return </span><span class="s1">umath.geterrobj()[</span><span class="s4">2</span><span class="s1">]</span>


<span class="s2">class </span><span class="s1">_unspecified:</span>
    <span class="s2">pass</span>


<span class="s1">_Unspecified = _unspecified()</span>


<span class="s1">@set_module(</span><span class="s3">'numpy'</span><span class="s1">)</span>
<span class="s2">class </span><span class="s1">errstate(contextlib.ContextDecorator):</span>
    <span class="s0">&quot;&quot;&quot; 
    errstate(**kwargs) 
 
    Context manager for floating-point error handling. 
 
    Using an instance of `errstate` as a context manager allows statements in 
    that context to execute with a known error handling behavior. Upon entering 
    the context the error handling is set with `seterr` and `seterrcall`, and 
    upon exiting it is reset to what it was before. 
 
    ..  versionchanged:: 1.17.0 
        `errstate` is also usable as a function decorator, saving 
        a level of indentation if an entire function is wrapped. 
        See :py:class:`contextlib.ContextDecorator` for more information. 
 
    Parameters 
    ---------- 
    kwargs : {divide, over, under, invalid} 
        Keyword arguments. The valid keywords are the possible floating-point 
        exceptions. Each keyword should have a string value that defines the 
        treatment for the particular error. Possible values are 
        {'ignore', 'warn', 'raise', 'call', 'print', 'log'}. 
 
    See Also 
    -------- 
    seterr, geterr, seterrcall, geterrcall 
 
    Notes 
    ----- 
    For complete documentation of the types of floating-point exceptions and 
    treatment options, see `seterr`. 
 
    Examples 
    -------- 
    &gt;&gt;&gt; olderr = np.seterr(all='ignore')  # Set error handling to known state. 
 
    &gt;&gt;&gt; np.arange(3) / 0. 
    array([nan, inf, inf]) 
    &gt;&gt;&gt; with np.errstate(divide='warn'): 
    ...     np.arange(3) / 0. 
    array([nan, inf, inf]) 
 
    &gt;&gt;&gt; np.sqrt(-1) 
    nan 
    &gt;&gt;&gt; with np.errstate(invalid='raise'): 
    ...     np.sqrt(-1) 
    Traceback (most recent call last): 
      File &quot;&lt;stdin&gt;&quot;, line 2, in &lt;module&gt; 
    FloatingPointError: invalid value encountered in sqrt 
 
    Outside the context the error handling behavior has not changed: 
 
    &gt;&gt;&gt; np.geterr() 
    {'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'} 
 
    &quot;&quot;&quot;</span>

    <span class="s2">def </span><span class="s1">__init__(self</span><span class="s2">, </span><span class="s1">*</span><span class="s2">, </span><span class="s1">call=_Unspecified</span><span class="s2">, </span><span class="s1">**kwargs):</span>
        <span class="s1">self.call = call</span>
        <span class="s1">self.kwargs = kwargs</span>

    <span class="s2">def </span><span class="s1">__enter__(self):</span>
        <span class="s1">self.oldstate = seterr(**self.kwargs)</span>
        <span class="s2">if </span><span class="s1">self.call </span><span class="s2">is not </span><span class="s1">_Unspecified:</span>
            <span class="s1">self.oldcall = seterrcall(self.call)</span>

    <span class="s2">def </span><span class="s1">__exit__(self</span><span class="s2">, </span><span class="s1">*exc_info):</span>
        <span class="s1">seterr(**self.oldstate)</span>
        <span class="s2">if </span><span class="s1">self.call </span><span class="s2">is not </span><span class="s1">_Unspecified:</span>
            <span class="s1">seterrcall(self.oldcall)</span>


<span class="s2">def </span><span class="s1">_setdef():</span>
    <span class="s1">defval = [UFUNC_BUFSIZE_DEFAULT</span><span class="s2">, </span><span class="s1">ERR_DEFAULT</span><span class="s2">, None</span><span class="s1">]</span>
    <span class="s1">umath.seterrobj(defval)</span>


<span class="s5"># set the default values</span>
<span class="s1">_setdef()</span>
</pre>
</body>
</html>