<html>
<head>
<title>test_argparse.py</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
.s0 { color: #629755; font-style: italic;}
.s1 { color: #a9b7c6;}
.s2 { color: #cc7832;}
.s3 { color: #6a8759;}
.s4 { color: #6897bb;}
.s5 { color: #808080;}
</style>
</head>
<body bgcolor="#2b2b2b">
<table CELLSPACING=0 CELLPADDING=5 COLS=1 WIDTH="100%" BGCOLOR="#606060" >
<tr><td><center>
<font face="Arial, Helvetica" color="#000000">
test_argparse.py</font>
</center></td></tr></table>
<pre><span class="s0">&quot;&quot;&quot; 
Tests for the private NumPy argument parsing functionality. 
They mainly exists to ensure good test coverage without having to try the 
weirder cases on actual numpy functions but test them in one place. 
 
The test function is defined in C to be equivalent to (errors may not always 
match exactly, and could be adjusted): 
 
    def func(arg1, /, arg2, *, arg3): 
        i = integer(arg1)  # reproducing the 'i' parsing in Python. 
        return None 
&quot;&quot;&quot;</span>

<span class="s2">import </span><span class="s1">pytest</span>

<span class="s2">import </span><span class="s1">numpy </span><span class="s2">as </span><span class="s1">np</span>
<span class="s2">from </span><span class="s1">numpy.core._multiarray_tests </span><span class="s2">import </span><span class="s1">argparse_example_function </span><span class="s2">as </span><span class="s1">func</span>


<span class="s2">def </span><span class="s1">test_invalid_integers():</span>
    <span class="s2">with </span><span class="s1">pytest.raises(TypeError</span><span class="s2">,</span>
            <span class="s1">match=</span><span class="s3">&quot;integer argument expected, got float&quot;</span><span class="s1">):</span>
        <span class="s1">func(</span><span class="s4">1.</span><span class="s1">)</span>
    <span class="s2">with </span><span class="s1">pytest.raises(OverflowError):</span>
        <span class="s1">func(</span><span class="s4">2</span><span class="s1">**</span><span class="s4">100</span><span class="s1">)</span>


<span class="s2">def </span><span class="s1">test_missing_arguments():</span>
    <span class="s2">with </span><span class="s1">pytest.raises(TypeError</span><span class="s2">,</span>
            <span class="s1">match=</span><span class="s3">&quot;missing required positional argument 0&quot;</span><span class="s1">):</span>
        <span class="s1">func()</span>
    <span class="s2">with </span><span class="s1">pytest.raises(TypeError</span><span class="s2">,</span>
            <span class="s1">match=</span><span class="s3">&quot;missing required positional argument 0&quot;</span><span class="s1">):</span>
        <span class="s1">func(arg2=</span><span class="s4">1</span><span class="s2">, </span><span class="s1">arg3=</span><span class="s4">4</span><span class="s1">)</span>
    <span class="s2">with </span><span class="s1">pytest.raises(TypeError</span><span class="s2">,</span>
            <span class="s1">match=</span><span class="s3">r&quot;missing required argument \'arg2\' \(pos 1\)&quot;</span><span class="s1">):</span>
        <span class="s1">func(</span><span class="s4">1</span><span class="s2">, </span><span class="s1">arg3=</span><span class="s4">5</span><span class="s1">)</span>


<span class="s2">def </span><span class="s1">test_too_many_positional():</span>
    <span class="s5"># the second argument is positional but can be passed as keyword.</span>
    <span class="s2">with </span><span class="s1">pytest.raises(TypeError</span><span class="s2">,</span>
            <span class="s1">match=</span><span class="s3">&quot;takes from 2 to 3 positional arguments but 4 were given&quot;</span><span class="s1">):</span>
        <span class="s1">func(</span><span class="s4">1</span><span class="s2">, </span><span class="s4">2</span><span class="s2">, </span><span class="s4">3</span><span class="s2">, </span><span class="s4">4</span><span class="s1">)</span>


<span class="s2">def </span><span class="s1">test_multiple_values():</span>
    <span class="s2">with </span><span class="s1">pytest.raises(TypeError</span><span class="s2">,</span>
            <span class="s1">match=</span><span class="s3">r&quot;given by name \('arg2'\) and position \(position 1\)&quot;</span><span class="s1">):</span>
        <span class="s1">func(</span><span class="s4">1</span><span class="s2">, </span><span class="s4">2</span><span class="s2">, </span><span class="s1">arg2=</span><span class="s4">3</span><span class="s1">)</span>


<span class="s2">def </span><span class="s1">test_string_fallbacks():</span>
    <span class="s5"># We can (currently?) use numpy strings to test the &quot;slow&quot; fallbacks</span>
    <span class="s5"># that should normally not be taken due to string interning.</span>
    <span class="s1">arg2 = np.unicode_(</span><span class="s3">&quot;arg2&quot;</span><span class="s1">)</span>
    <span class="s1">missing_arg = np.unicode_(</span><span class="s3">&quot;missing_arg&quot;</span><span class="s1">)</span>
    <span class="s1">func(</span><span class="s4">1</span><span class="s2">, </span><span class="s1">**{arg2: </span><span class="s4">3</span><span class="s1">})</span>
    <span class="s2">with </span><span class="s1">pytest.raises(TypeError</span><span class="s2">,</span>
            <span class="s1">match=</span><span class="s3">&quot;got an unexpected keyword argument 'missing_arg'&quot;</span><span class="s1">):</span>
        <span class="s1">func(</span><span class="s4">2</span><span class="s2">, </span><span class="s1">**{missing_arg: </span><span class="s4">3</span><span class="s1">})</span>

</pre>
</body>
</html>